### ISSUE TITLE
[Gesture Indicator] Option to turn off certain gestures from showing.

### ISSUE THREAD

**Issue by ThatsNotAName** [ImTiara/CVRMods#3]
With index controllers my hands are generally always open when playing, meaning I almost always have the open hand gesture. I don't put any gestures on this specific one for that reason so I was wondering if it would be possible to selectively true or false certain gestures from showing on the indicator UI? If not its all good just a little QOL thing that would help clear up the hud of unnecessary info.

**Comment by ImTiara** [comment]
This will most likely not be implemented.
However if you know how to, feel free to download the source and build a version of the mod that fits your situation.
